on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Install rust target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions/checkout@v4
    - run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - name: Publish
      run: cargo publish